bufbuild/plugins

- .github/workflows/deploy.yml
This PR adds GitHub Action workflow to deploy a plugin to the BSR.
The `plugin-directory` is expected to be the versioned directory. E.g., `library/connect-go/v0.4.0`
Eventually we'll want to trigger this on merges to main, and optionally, only build/deploy changed directories. Alternative, we can deploy the kitchen sink and rely on BSR to resolve the plugin state.
> Add workflow to deploy plugin

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- contrib/chrusty/jsonschema/v1.3.9/Dockerfile
- library/connect-go/v0.1.1/Dockerfile
- library/connect-go/v0.2.0/Dockerfile
- library/connect-go/v0.3.0/Dockerfile
- library/connect-go/v0.4.0/Dockerfile
- library/go/v1.28.0/Dockerfile
- library/go/v1.28.1/Dockerfile
- library/grpc-go/v1.2.0/Dockerfile
Go 1.19 introduces new formatting of doc comments. Upgrade plugins so
that they match the latest formatted code.
> update to build go plugins with 1.19

- library/connect-go/v0.1.1/Dockerfile
- library/connect-go/v0.2.0/Dockerfile
- library/connect-go/v0.3.0/Dockerfile
- library/connect-go/v0.4.0/Dockerfile
Update the connect-go plugins to specify -trimpath to hopefully avoid
small differences in published images.
> specify -trimpath when building connect-go

- .github/workflows/deploy.yml
We'll need to authenticate to ghcr.io when using --cache-from.
> login to ghcr.io when building image

- .github/dependabot.yml
Update the dependabot config to point at Docker image updates for each
unique base image (i.e. go, node, debian, swift, dart, java). This
should alert us when new base images are available but we'll still want
to bump versions in unison across all the plugins.
> add dependabot config for unique docker bases

- cmd/fetcher/main.go
- internal/fetchclient/fetchclient.go
- internal/source/config.go
This PR adds a new source.yaml option to allow including prerelease versions.
If the latest fetched version is a prerelease, and `include_prerelease: true` is not set then we log it and ignore.
> Exclude prereleases by default

- .github/workflows/ci.yml
- Makefile
Update the CI workflow (when changes are pushed to the main branch) to
run the `buf alpha plugin push` command (in dependency order) to push
all plugins to the BSR.
> run buf alpha plugin push on CI workflow

- Makefile
Don't append 'bufbuild' to docker pull command and fail push if we can't
pull the image from the registry. Consistently use $(DOCKER) and add a
$(BUF) command as well for easy testing.
> update docker pull command

- library/connect-web/v0.0.10/buf.plugin.yaml
- library/connect-web/v0.1.0/buf.plugin.yaml
- library/protobuf-es/v0.0.10/buf.plugin.yaml
- library/protobuf-es/v0.0.9/buf.plugin.yaml
Chatted with @timostamm today, and something we want to start doing is capturing runtime dependencies with a caret to loosen the acceptable semver range.
There are special rules for pre-v1 and caret, so this would lead to bumps in the the patch version only. But this is the direction we want to go in once the plugin runtime hits v1 anyways.
> Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. In other words, this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.
Ref: https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004
In the BSR NPM registry this is exposed as a peer dependency.
> Use caret in npm registry peer deps

- .github/workflows/ci.yml
Continue to build and test _all_ plugins on merge to main, but do not do a subsequent push.
> Remove pushing all plugins

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- Makefile
Switch from Docker inline buildkit cache to using the registry cache
with a separate image. This allows us to cache more layers (mode=max)
and also hopefully avoid issues seen with unreproducible builds given
the same inputs.
> stop using Docker inline buildkit cache

- Makefile
We should continue to maintain a separate buildcache for each version of
a plugin or base image.
> add version to buildcache tag for plugins

- Makefile
- library/grpc/v1.48.0/base/Dockerfile
- library/protoc/v21.3/base/Dockerfile
- library/protoc/v21.4/base/Dockerfile
- library/protoc/v21.5/base/Dockerfile
- library/protoc/v3.20.1/base/Dockerfile
Diffing two base layer versions is showing the only changes to the
"created" time for the VERSION arg and the test using it right below.
Remove this and hardcode the version in the base Dockerfile for now to
see if this works around the issue.
> attempt to workaround another build issue

- go.mod
- go.sum
- library/grpc-go/v1.2.0/buf.plugin.yaml
Update grpc-go plugin to specify registry opts (including
'separate_package=true').
> configure registry opts for grpc-go

- .github/workflows/ci.yml
Update the ci workflow to use concurrency to ensure that only a single
build is running at a time.
> prevent concurrent builds on main branch

- library/connect-web/v0.0.10/Dockerfile
- library/connect-web/v0.1.0/Dockerfile
- library/connect-web/v0.2.0/Dockerfile
- library/protobuf-es/v0.0.10/Dockerfile
- library/protobuf-es/v0.0.9/Dockerfile
- library/protobuf-es/v0.1.0/Dockerfile
- library/protobuf-es/v0.1.1/Dockerfile
Update node plugins to use a multi-stage build even though we're using package.json/package-lock.json to control dependency versions. There still might be state stored during the `npm ci` operation that we don't want to exist in the final runtime image.
This doesn't make a huge difference but it does reduce the image size by 2-3mb and will hopefully remove additional places where we'll have Docker image build cache misses.
> always use multi-stage builds for node plugins

- CONTRIBUTING.md
- Makefile
- cmd/dependency-order/main.go
- internal/plugin/plugin.go
- internal/plugin/plugin_test.go
- tests/plugins_test.go
Make it easier to build/test/push specific plugins by introducing a new `PLUGINS` argument to the Makefile. For example, to build all versions of connect-go and a single version of protobuf-es, run:
$ make PLUGINS="connect-go protobuf-es:v0.1.1"
Additionally, update all push targets to use the `--image` flag for consistency.
> allow building/testing specific plugins

- internal/plugin/plugin.go
- internal/plugin/plugin_test.go
When building specific plugins, allow using 'latest' instead of a semantic version to only build the latest version of a given plugin. For example, `make PLUGINS="connect-web:latest"` will only build the latest version of connect-web.
> allow specifying 'latest' as plugin version

- library/connect-web/v0.0.10/Dockerfile
- library/connect-web/v0.1.0/Dockerfile
- library/connect-web/v0.2.0/Dockerfile
- library/connect-web/v0.2.1/Dockerfile
- library/protobuf-es/v0.0.10/Dockerfile
- library/protobuf-es/v0.0.9/Dockerfile
- library/protobuf-es/v0.1.0/Dockerfile
- library/protobuf-es/v0.1.1/Dockerfile
- library/twirp-go/v8.1.2/Dockerfile
Update plugins that aren't using PLUGIN_VERSION to remove their usage to minimize chances of re-publishing plugins due to Docker image config JSON changes.
> remove unused PLUGIN_VERSION argument

- .github/workflows/fetch_versions.yml
- cmd/fetcher/main.go
- contrib/chrusty/jsonschema/source.yaml
- go.mod
- go.sum
- internal/fetchclient/fetchclient.go
- internal/source/source.go
- internal/source/source_test.go
Update the fetch_versions client to support fetching from the top-level directory (so contrib versions can be updated too). Add support for using GITHUB_TOKEN for authentication (to avoid rate limit issues). Do a replace across all files of the old version with the new version when creating the files for a new plugin.
> improve the fetch_versions client

- CONTRIBUTING.md
Update the documentation for contributing to this repository to use the `PLUGINS` makefile variable to only build/test the new/updated plugin and not build all plugins in the project.
> update contributing documentation

- .github/workflows/fetch_versions.yml
Don't specify a `branch-suffix` so the default behavior is used (only one branch will be created and it will be updated as needed).
> only create a single branch for plugin updates

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- .github/workflows/push_all.yml
PRs raised from forks of the repository don't have permission to use secrets for Docker Hub. Update the PR workflow to make logging in to Docker Hub conditional (the build should still work but may be subject to rate limiting).
Update to use docker-login-action consistently in other places to log into the GitHub container registry.
> conditionally log in to dockerhub for PRs

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- .github/workflows/push_all.yml
In order to use newer features of the buf CLI that haven't been released yet, we're building the CLI from the main branch. However, we're restoring Go module cache after we install the CLI which means that we're not benefiting from previous builds.
Update the workflows to configure the Go module cache before running 'go install'.
> configure go module cache before installing buf CLI

- .github/workflows/fetch_versions.yml
We use the buf CLI in order to test code generation of newer plugins. Update the workflow to install Go, cache Go modules, and install the latest buf CLI.
> install buf CLI as part of fetch versions

- cmd/fetcher/main.go
When we generate diffs from the previous generated code to the new generated code, we should allow the command to return an exit code of 1. Diff will return 1 when there are diffs, 0 when there are no diffs, and anything else if there are other errors.
> update fetcher to allow non-zero exit code from diff

- cmd/release/main.go
If we fail to retrieve the latest image digest for a plugin, continue processing other plugins. This might help identify issues with ghcr container access with github actions.
> allow release to continue on 404

- cmd/release/main.go
Update the release notes body to collapse previously released plugins so users can focus on just what changed.
> collapse previously released plugins

- .gitignore
- .golangci.yml
- cmd/download-plugins/main.go
- cmd/release/main.go
- internal/release/github.go
- internal/release/minisign.pub
- internal/release/publickey.go
- internal/release/release.go
Create a download-plugins CLI which can be used to download the latest plugins from GitHub (and verify both the signature of plugin-releases.json and the SHA-256 sums of each zip file).
As part of this work, refactor reusable code from the current release command into the internal/release package.
> add a utility to download plugins from GitHub

- .github/workflows/ci.yml
Migrate from last-successful-commit-action to nx-set-shas. This reflects upstream changes made in tj-actions/changed-files:
https://github.com/tj-actions/changed-files/pull/822
> migrate off deprecated github action

- cmd/download-plugins/main.go
- internal/fetchclient/fetchclient.go
- internal/release/github.go
Remove DEBUG logging of every HTTP request. Don't log when the plugin exists on disk with the right checksum. Set plugin timestamps to reflect when they were released (this may make it easier to determine which plugins to install or update).
> small improvements to download-plugins

- internal/fetchclient/fetchclient.go
Update the fetch client to check the status code of responses before trying to parse them. Log more details about errors for the Maven fetch implementation as we're seeing regular issues there and it would help to diagnose further (perhaps rate limiting?).
> check http status code of responses

- plugins/bufbuild/validate-cpp/v0.9.0/buf.plugin.yaml
- plugins/bufbuild/validate-go/v0.9.0/buf.plugin.yaml
- plugins/bufbuild/validate-java/v0.9.0/buf.plugin.yaml
- plugins/grpc/cpp/v1.51.1/buf.plugin.yaml
- plugins/grpc/csharp/v1.51.1/buf.plugin.yaml
- plugins/grpc/java/v1.51.1/buf.plugin.yaml
- plugins/grpc/kotlin/v1.3.0/buf.plugin.yaml
- plugins/grpc/objc/v1.51.1/buf.plugin.yaml
- plugins/grpc/php/v1.51.1/buf.plugin.yaml
- plugins/grpc/python/v1.51.1/buf.plugin.yaml
- plugins/grpc/ruby/v1.51.1/buf.plugin.yaml
- plugins/grpc/swift/v1.13.1/buf.plugin.yaml
Even though these plugins don't yet support remote packages, we should add dependencies so that the 'Include Dependencies' works as expected on the plugin details pages. All of these plugins require base types generated from another plugin.
> add missing plugin dependencies

- .github/workflows/pr.yml
PRs from GitHub forks don't have access to GitHub actions secrets.
> conditional login to dockerhub

- plugins/community/neoeinstein-prost/source.yaml
- plugins/community/neoeinstein-prost/v0.2.1/.dockerignore
- plugins/community/neoeinstein-prost/v0.2.1/Dockerfile
- plugins/community/neoeinstein-prost/v0.2.1/buf.plugin.yaml
- tests/testdata/buf.build/community/neoeinstein-prost/v0.2.1/eliza/plugin.sum
- tests/testdata/buf.build/community/neoeinstein-prost/v0.2.1/petapis/plugin.sum
This PR adds the `protoc-gen-prost` plugin. 
Note, I'll tackle [tonic](https://crates.io/crates/protoc-gen-tonic) and [serde](https://crates.io/crates/protoc-gen-prost-serde) from #255 in a subsequent PR as it'll require another solution that is orthogonal to getting this plugin merged in.
> Adds protoc-gen-prost v0.2.1

- plugins/community/neoeinstein-prost/v0.2.1/buf.plugin.yaml
This PR updates the source_url to GitHub for the prost plugin to be consistent with other plugins.
> Update prost source_url to GitHub

- plugins/grpc-ecosystem/gateway/source.yaml
Use the same configuration as protoc-gen-openapiv2 (which comes from the same repository).
> fix fetch versions for grpc-gateway

- cmd/release/main.go
- internal/release/release.go
In order to optimize lookups, we should add dependency information to the plugin-releases.json file. This will allow us to avoid scanning every .zip file to parse the buf.plugin.yaml.
> Add plugin dependencies to releases file

- .github/workflows/release.yml
- .github/workflows/upload.yml
Update the release workflow to call the upload workflow when a release is completed. Add an upload workflow which downloads (and caches) the latest release and uses `gsutil rsync` to copy its contents to a GCS bucket.
> Upload release to GCS bucket

- cmd/download-plugins/main.go
- cmd/release/main.go
- internal/release/github.go
As part of downloading plugins, we should download the corresponding metadata files - plugin-releases.json and plugin-releases.json.minisig.
> Download plugin-releases.json.*

- .github/workflows/upload.yml
The release workflow isn't noticing when new plugins are updated. We should update the configuration of the cache action to create a new cache when the plugins change.
> Attempt to fix caching plugins

- plugins/grpc-ecosystem/gateway/v2.15.0/buf.plugin.yaml
The source_url in buf.plugin.yaml for grpc-gateway seemed to be wrong, so I fixed it.
> Fix source_url in grpc-ecosystem/grpc-gateway

- tests/plugins_test.go
Currently, if running the plugin fails for any reason, we continue the tests and fail with an error about the 'gen' directory not existing. We should fail fast to make it more apparent what caused the test failure.
> Fail fast if plugin execution fails

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- CONTRIBUTING.md
- Makefile
- internal/cmd/changed-plugins/main.go
- internal/plugin/plugin.go
- internal/plugin/plugin_test.go
- tests/plugins_test.go
Add support for workflow_dispatch (manual builds) to specify the PLUGINS env var to allow for rebuilding certain plugins (bypassing the default logic that uses changed-files actions to determine what to rebuild).
Update the changed-files action to run just once and print out a value which can be used as the PLUGINS env var. This allows us to isolate this logic around github actions to just a single place in the code.
Update places that decide which plugins to run to be more conservative. If no filter parameters are used, don't build any plugins and show an error message. This should make it better for new contributors to this project to more easily get started with building a specific plugin (since no one should really be building all 300+ plugins at this point unless they really mean to …
> Simplify plugins build process

- .github/workflows/ci.yml
- .github/workflows/pr.yml
Update the GitHub action workflows to ignore use of changed-files action if we've already gotten a non-empty input to the workflow.
> Ignore changed-files calculation for manual build

- .github/workflows/ci.yml
- Makefile
- internal/cmd/dockerbuild/main.go
- internal/cmd/dockerpush/main.go
- internal/docker/build.go
- internal/docker/dockerfile.go
- internal/docker/dockerfile_test.go
- internal/docker/name.go
- internal/docker/plugindocker.go
- internal/docker/push.go
Currently, we're re-running the docker build with the '--push' argument, which unfortunately both triggers a rebuild and pushes the images for the other stages of the Dockerfile (which can be much larger than the actual plugin image).
Add a new utility `dockerpush` to run after `dockerbuild` which only does the push of pre-built images. This should speed up the build and also reduce what we push to GHCR.
> Add dockerpush command to run after dockerbuild

- .github/workflows/fetch_versions.yml
- .github/workflows/release.yml
I suggest we change the Fetcher to run in the morning 10AM eastern, that way we get a notification to remind us on the same day (instead of 8PM the night before).
And update the Release workflow to run every hour, so from the time we merge the PR it gets release. Although maybe this one we can reduce to 4 hours, no strong preference.
> Update cron intervals

- .github/workflows/release.yml
- internal/cmd/release/main.go
In order to prevent race conditions where commits may be merged at the same time a release is running, always pass the `github.sha` as an argument to the release command.
> Create release from GitHub commit

- cmd/download-plugins/main.go
- internal/plugin/plugin.go
In order to only download a subset of plugins, update download-plugins to support the same PLUGINS env var supported by other commands. If the env var isn't set or is set to 'all', then no filtering is performed.
> Allow download-plugins to use PLUGINS env var

- cmd/download-plugins/main.go
The plugin-releases.json file only has the "{owner}/{plugin}", not the leading "{remote}". For the purposes of matching, we should include the "{remote}/" prefix for consistency.
> Prepend buf.build/ when matching plugins

- .github/workflows/ci.yml
Disable calculation of changed files, as the last commit on main is failing to build successfully even after several retries. After splitting the changes into two builds to build the protoc artifacts separate from the grpc artifacts the build succeeded, however newer builds are still running with the previous state.
Temporarily disable use of changed-files github action for one build to get a successful run.
> Disable changed files calculation to reset state

- internal/plugin/plugin.go
- internal/plugin/plugin_test.go
- tests/plugins_test.go
Improve the handling of the PLUGINS variable to allow either space or comma separated plugin(s). Update name validation to prevent use of underscores which will cause issues with remote packages in some languages.
> Improve PLUGINS var handling and validate names

- .github/workflows/ci.yml
- .github/workflows/pr.yml
We are no longer doing anything special with our builds - change our buildx configuration to the default.
> Use docker buildx defaults

- internal/docker/build.go
In order to test against Docker images, we need to save them to the local Docker host.
> Use buildx --load command

- plugins/grpc/kotlin/v1.3.0/buf.plugin.yaml
The grpc/kotlin plugin currently doesn't work with remote packages, as it was dependent on a version of protocolbuffers/kotlin that didn't include a fix for #491. Update this plugin to depend on newer dependencies so that it can work with remote packages.
> Update grpc/kotlin to newer dependencies

- .github/workflows/fetch_versions.yml
We should use the same Docker config in all the PR jobs that build Docker images.
> Set up Docker buildx in fetch_versions

- plugins/protocolbuffers/pyi/v23.2/BUILD
- plugins/protocolbuffers/pyi/v23.2/pyi.cc
We're inconsistently seeing issues when building .php and .pyi together again - ensure that the BUILD and .cc files have different file sizes to ensure Docker doesn't mix contexts from both builds.
> Add comments to pyi plugin files

- plugins/apple/swift/v1.22.0/.dockerignore
- plugins/apple/swift/v1.22.0/Dockerfile
- plugins/apple/swift/v1.22.0/buf.plugin.yaml
- plugins/apple/swift/v1.22.0/extramoduleimports.patch
- tests/testdata/buf.build/apple/swift/v1.22.0/eliza/plugin.sum
- tests/testdata/buf.build/apple/swift/v1.22.0/petapis/plugin.sum
Update the patch to cleanly apply against apple/swift v1.22.0.
> Add swift v1.22.0 with updated patch

- internal/cmd/fetcher/main.go
When fetch versions runs for gRPC or protoc plugins, we can optimize the build time significantly by building them in sequence instead of individually. Update fetch versions to build/test all new plugins together instead of individually.
> Build plugins in batch

- .golangci.yml
- cmd/download-plugins/main.go
- go.mod
- go.sum
- internal/cmd/fetcher/main.go
- internal/cmd/release/main.go
- internal/fetchclient/fetchclient.go
- internal/plugin/plugin.go
- internal/release/github.go
Now that we have a Dockerfile.bazel that is kept up to date with dependabot, we can automate upgrades for packages that use Bazel.
> Automate bazel upgrades

- plugins/community/neoeinstein-prost-crate/source.yaml
- plugins/community/neoeinstein-prost-crate/v0.3.1/.dockerignore
- plugins/community/neoeinstein-prost-crate/v0.3.1/Dockerfile
- plugins/community/neoeinstein-prost-crate/v0.3.1/buf.plugin.yaml
- tests/plugins_test.go
- tests/testdata/buf.build/community/neoeinstein-prost-crate/v0.3.1/eliza/plugin.sum
- tests/testdata/buf.build/community/neoeinstein-prost-crate/v0.3.1/petapis/plugin.sum
add neoeinstein-prost-crate to community plugins
Closes #608
> Add neoeinstein-prost-crate v0.3.1 plugin

- .github/docker/Dockerfile.debian
- .github/docker/Dockerfile.golang
Debian 12 (bookworm) is now stable. We should update our builds to start using this going forward.
> Update to latest debian stable release

- plugins/protocolbuffers/kotlin/v23.1/buf.plugin.yaml
- plugins/protocolbuffers/kotlin/v23.2/buf.plugin.yaml
- plugins/protocolbuffers/kotlin/v23.3/buf.plugin.yaml
We should ensure that we pull in both kotlin-stdlib AND kotlin-stdlib-jdk8 to ensure that consistent versions are used with the dependencies and the compiler. Without this, it is possible that protobuf-kotlin's dependency version kotlin-stdlib 1.6.0 is used instead.
Breaking this change into multiple PRs as these plugins take a long time to build.
> Add kotlin-stdlib in addition to jdk8 variant

- plugins/protocolbuffers/kotlin/v22.4/buf.plugin.yaml
- plugins/protocolbuffers/kotlin/v23.0/buf.plugin.yaml
We should ensure that we pull in both kotlin-stdlib AND kotlin-stdlib-jdk8 to ensure that consistent versions are used with the dependencies and the compiler. Without this, it is possible that protobuf-kotlin's dependency version kotlin-stdlib 1.6.0 is used instead.
Breaking this change into multiple PRs as these plugins take a long time to build.
> Add kotlin-stdlib in addition to jdk8 variant v2

- plugins/protocolbuffers/kotlin/v22.2/buf.plugin.yaml
- plugins/protocolbuffers/kotlin/v22.3/buf.plugin.yaml
We should ensure that we pull in both kotlin-stdlib AND kotlin-stdlib-jdk8 to ensure that consistent versions are used with the dependencies and the compiler. Without this, it is possible that protobuf-kotlin's dependency version kotlin-stdlib 1.6.0 is used instead.
Breaking this change into multiple PRs as these plugins take a long time to build.
> Add kotlin-stdlib in addition to jdk8 variant v3

- .github/docker/Dockerfile.debian
- .github/docker/Dockerfile.golang
Seeing build errors from protoc plugins with the latest Debian version release. Try reverting back to bullseye to fix.
Hoping this will resolve #637.
> Revert upgrade to latest Debian LTS

- plugins/bufbuild/connect-kotlin/v0.1.8/buf.plugin.yaml
- plugins/grpc/kotlin/v1.3.0/buf.plugin.yaml
Update plugin dependencies for connect-kotlin and grpc-kotlin to pull in the latest version of the protocolbuffers/kotlin v23.4 plugin (which contains a patch for Kotlin package names).
> Update connect-kotlin and grpc-kotlin deps

- plugins/bufbuild/connect-go/source.yaml
Disable fetching new versions for bufbuild/connect-go, this plugin is now being synced to connectrpc/go
> Disable fetcher for bufbuild/connect-go

- .github/workflows/fetch_versions.yml
- internal/cmd/dockerbuild/main.go
- internal/cmd/fetcher/main.go
To make the best use of the Docker build cache, we should build protoc/grpc bazel plugins serially. Today we group them by version, however some builds of the fetch versions job appear to get hung up building the old/new versions of these plugins concurrently, leading to very long build times.
> Build protoc/grpc bazel plugins serially

- internal/cmd/fetcher/main.go
- internal/fetchclient/fetchclient.go
Small fix to the fetcher to handle pre-release versions properly.
Fix #806
> 2023/09/13 10:43:30 skipping source: plugins/connectrpc/es/source.yaml: npm_registry: pre-release versions are not supported: v1.0.0-rc1
2023/09/13 10:43:30 finished running in: 0.79s
We handle the error gracefully and skip the version.
> Update fetcher to skip pre-release versions

- .github/workflows/fetch_versions.yml
The previous 'repository' input has been replaced with two new inputs, 'installation_retrieval_mode' and 'installation_retrieval_payload'. The defaults for these values are the same as the previous 'repository' input, so we can remove this to fix warnings with the fetch versions workflow.
> Update inputs for tibdex/github-app-token

- internal/cmd/dockerbuild/main.go
- internal/cmd/release/main.go
- internal/docker/build.go
- internal/docker/name.go
- internal/docker/push.go
- internal/plugin/plugin.go
It appears than non-bazel builds aren't getting use of the local cache as well as other builds. Update the dockerbuild command to create unique cache directories per plugin and version, and reinstate the ability to build images in parallel.
> Add a per-plugin cache

- plugins/community/google-gnostic-openapi/source.yaml
- plugins/community/google-gnostic-openapi/v0.7.0/.dockerignore
- plugins/community/google-gnostic-openapi/v0.7.0/Dockerfile
- plugins/community/google-gnostic-openapi/v0.7.0/buf.plugin.yaml
- tests/testdata/buf.build/community/google-gnostic-openapi/v0.7.0/eliza/plugin.sum
- tests/testdata/buf.build/community/google-gnostic-openapi/v0.7.0/petapis/plugin.sum
> Add protoc-gen-openapi v0.7.0

- .github/workflows/arm64.yml
- .github/workflows/ci.yml
- .github/workflows/fetch_versions.yml
- .github/workflows/pr.yml
The changes required for integration guides landed in v1.27.2, so we can move back to the standard buf-setup-action in CI builds.
> Re-enable the buf-setup-action in CI workflows

- plugins/apple/swift/v1.25.1/.dockerignore
- plugins/apple/swift/v1.25.1/Dockerfile
- plugins/apple/swift/v1.25.1/buf.plugin.yaml
- plugins/apple/swift/v1.25.1/extramoduleimports.patch
- tests/testdata/buf.build/apple/swift/v1.25.1/eliza/plugin.sum
- tests/testdata/buf.build/apple/swift/v1.25.1/petapis/plugin.sum
This PR makes a slight update to the patch because of a merge conflict due to upstream changes.
Here's a diff between the current patch and the [v1.24.0 patch](https://github.com/bufbuild/plugins/blob/8da3b86ff10619c1beb0a6cea9cc59a819be3be1/plugins/apple/swift/v1.24.0/extramoduleimports.patch#L1)
```diff
--- A/extramoduleimports-3.patch
+++ B/extramoduleimports-4.patch
@@ -17,10 +17,10 @@
p.print("\n")
generateVersionCheck(printer: &p)
diff --git a/Sources/protoc-gen-swift/GeneratorOptions.swift b/Sources/protoc-gen-swift/GeneratorOptions.swift
+index 7b7b4bad..969dc0c1 100644
-index 69ecdb86..e0f2e26e 100644
--- a/Sources/protoc-gen-swift/GeneratorOptions.swift
+++ b/Sources/protoc-gen-swift/GeneratorOptions.swift
+@@ -53,6 +53,7 @@ class GeneratorOptions {
-@@ -50,6 +50,7 @@ class …
```
> Add apple/swift v1.25.1

- Makefile
- internal/cmd/dockerbuild/main.go
- internal/cmd/fetcher/main.go
- internal/cmd/release/main.go
- internal/cmd/restore-release/main.go
- internal/docker/build.go
- internal/docker/push.go
- internal/plugin/plugin.go
- tests/plugins_test.go
Update the dockerbuild command to add a label containing the git revision of the plugin's directory (if there are no changes to the working directory of the plugin). If we determine that an image exists for the same revision of the plugin, skip costly rebuilds.
Additionally, update commands to use exec.CommandContext consistently and stop calling exec.LookPath as the exec package does this automatically for us if the command doesn't contain path separators.
> Only rebuild plugins if changed

- plugins/grpc/python/v1.59.2/buf.plugin.yaml
Missed this version, and added it to grpc v1.59.1. Oops.
> Add python registry config for grpc/python v1.59.2

- .github/docker/Dockerfile.debian
- .github/docker/Dockerfile.distroless-base-debian
- .github/docker/Dockerfile.distroless-cc-debian
- .github/docker/Dockerfile.distroless-java-debian
- .github/docker/Dockerfile.distroless-nodejs-debian
- .github/docker/Dockerfile.distroless-static-debian
- .github/docker/Dockerfile.golang
- .github/docker/Dockerfile.swift
In order to improve reproducibility of builds, we should start to track distroless image updates. Add docker files for each flavor of distroless images we're using (additional follow up work is necessary to the fetch versions command to replace old versions with new ones).
Update debian/golang to bookworm going forward and update swift to use a 22.04 base image instead of the 20.04 one.
> Start tracking distroless image updates

- internal/cmd/fetcher/main.go
- internal/docker/baseimage.go
- internal/docker/baseimage_test.go
- internal/docker/testdata/duplicatedistroless/Dockerfile.distroless-java11-debian
- internal/docker/testdata/duplicatedistroless/Dockerfile.distroless-java17-debian
- internal/docker/testdata/duplicateversions/Dockerfile.debian11
- internal/docker/testdata/duplicateversions/Dockerfile.debian12
Update fetcher to support updating distroless images to the latest versions (both the latest image name and version). Refactor some of the logic around loading base image versions into a separate package (with tests) to slim down the fetcher command some.
> Update fetcher to update distroless images

- .github/workflows/release.yml
A release may fail if another release created the github release/tag in the meantime. This doesn't have any negative effects, however we should avoid failed workflows and only run a single release job at a time.
Fixes #935.
> Prevent concurrent release jobs

- cmd/latest-plugins/main.go
- internal/release/release.go
Add a new `latest-plugins` CLI to determine the latest published plugins (and their dependencies) and output them as a JSON document to stdout. This will be used downstream by other utilities to package plugins for distribution.
> Add a utility to determine latest plugins

- .github/dependabot.yml
The distroless Docker images appear to be updated together. Group them into a single PR instead of 5.
> Group distroless updates together

- internal/plugin/plugin.go
- tests/plugins_test.go
This PR adds a defensive check in our plugin tests to avoid passing plugins that generate no code and produce an "empty dir" hash.
There is a historical allowlist of plugins we'll allow, but moving forward we should craft protos to exercise valid code generation, in a similar way as:
https://github.com/bufbuild/plugins/blob/d524f5ffe0e922ac10752db571b60a320f7fc7f4/tests/plugins_test.go#L133-L13
For context, this would help catch https://github.com/bufbuild/plugins/pull/1017 against the typical images we pass in testing.
> --- FAIL: TestGeneration (0.42s)
--- FAIL: TestGeneration/plugins/community/mercari-grpc-federation/v0.9.2 (0.00s)
--- FAIL: TestGeneration/plugins/community/mercari-grpc-federation/v0.9.2/eliza (0.83s)
plugins_test.go:99: generated code directory is empty for …
> Update test case for empty dir hash in gen dir

- plugins/community/mfridman-go-json/source.yaml
- plugins/community/mfridman-go-json/v1.2.0/.dockerignore
- plugins/community/mfridman-go-json/v1.2.0/Dockerfile
- plugins/community/mfridman-go-json/v1.2.0/buf.plugin.yaml
- plugins/community/mitchellh-go-json/source.yaml
- tests/testdata/buf.build/community/mfridman-go-json/v1.2.0/eliza/plugin.sum
- tests/testdata/buf.build/community/mfridman-go-json/v1.2.0/petapis/plugin.sum
This PR adds a new community plugin which supersedes the existing one mitchellh/protoc-gen-go-json. I've disabled further updates of that plugin, and will mark it deprecated shortly.
This should also resolve the upstream issue folks have been asking about. https://github.com/mitchellh/protoc-gen-go-json/issues/17
> Add community/mfridman-go-json v1.2.0

- .github/workflows/upload.yml
We updated the service account mapping internally and forgot to update it here.
> Fix service account

- .github/workflows/upload.yml
Optimize rsync job to pass the -m option to fix a build warning shown in the release logs.
> Pass -m option to gsutil rsync

- plugins/grpc/go/v1.3.0/Dockerfile
- plugins/grpc/go/v1.3.0/buf.plugin.yaml
Update grpc/go to require the earliest version of the google.golang.org/grpc dependency with security fixes (v1.61.2). Update the plugin dependency to the latest version of protocolbuffers/go. Improve dockerfile to support multi-arch builds.
Fixes #1210.
> Update grpc/go plugin to latest security release

- plugins/community/neoeinstein-tonic/v0.4.0/buf.plugin.yaml
Similar to grpc/go and connectrpc/go depending on protocolbuffers/go, tonic relies on prost codegen for the base message types.
Just adding this to the latest tonic version for now, but happy to go back and add it elsewhere (either here or as a follow-up).
> Add dependency on prost for tonic

- plugins/protocolbuffers/pyi/v27.0/buf.plugin.yaml
- plugins/protocolbuffers/python/v27.0/buf.plugin.yaml
Discussed this internally - we made the decision when releasing the Python Repository to not add a dependency between these plugins, specifically in the python->pyi direction, so that users that don't want type annotations don't need to have them included as a dependency.
However, if you _want_ type annotations, it's confusing to need to install both packages. Also, a `*_pyi` package is useless on its own (since it creates a [stub-only package][1]). Lastly, grpc/python comes with stubs built-in now, and protocolbuffers leans pretty heavily into types. Let's add this dependency relationship moving forward to simplify things for users.
For now, only adding this on the latest version - we can backport if there's significant interest.
[1]: https://peps.python.org/pep-0561/#stub-only-packages
> Add pb/py->pb/pyi dependencies

- plugins/protocolbuffers/python/v25.0/buf.plugin.yaml
- plugins/protocolbuffers/python/v25.1/buf.plugin.yaml
- plugins/protocolbuffers/python/v25.2/buf.plugin.yaml
- plugins/protocolbuffers/python/v25.3/buf.plugin.yaml
We're already doing this for the v26 ([e.g.](https://github.com/bufbuild/plugins/blob/313fe18533139a4b3a70516a3082de038c6c4a67/plugins/protocolbuffers/python/v26.1/buf.plugin.yaml#L17)) and v27 plugins. v25 is the earliest release currently supported by Generated SDKs, and is on the [4.x releases](https://pypi.org/project/protobuf/#history) of `protobuf` — this just makes it easier for users to pin to these versions when other dependencies rely on a lower version of `protobuf`.
v25 also happens to be the earliest version of the plugins with Generated SDK support, so now we're covering all of our existing bases with these compatible version specifiers.
> Backport Python `protobuf` compatible versions to v25.*

- tests/plugins_test.go
Plugins supporting generated SDKs for Go need to ensure they set a min_version to be equal to the greatest version of any of their declared dependencies.
> Validate plugin go min_version

- plugins/protocolbuffers/pyi/v27.2/buf.plugin.yaml
- plugins/protocolbuffers/python/v27.2/buf.plugin.yaml
Update the python plugins to ensure we require a dependency version of the protobuf library to be at least the same version of the gencode. Without this constraint, users that have an earlier 5.27.0 or 5.27.1 version of the protobuf dependency already installed will fail at runtime.
See https://protobuf.dev/support/cross-version-runtime-guarantee/ for more details.
> Require protobuf dep to be at least gencode level

- plugins/protocolbuffers/pyi/v26.1/Dockerfile
- plugins/protocolbuffers/pyi/v26.1/buf.plugin.yaml
- plugins/protocolbuffers/python/v26.1/Dockerfile
- plugins/protocolbuffers/python/v26.1/buf.plugin.yaml
Update python v26.1 plugin dependencies to pull in the same or later version of the protobuf library. While we're rebuilding plugins, reduce additional layers in the Python v26.1 plugins and add a dependency on pyi plugin to match updates in later versions.
Ref: https://github.com/bufbuild/plugins/pull/1319
> Fix python v26.1 plugin dependencies

- plugins/protocolbuffers/pyi/v27.1/buf.plugin.yaml
Now that there is a 5.x version available, update the buf.plugin.yaml to target a specific version.
> Specify version of types-protobuf

- plugins/grpc/go/v1.4.0/buf.plugin.yaml
The protoc-gen-grpc-go plugin updated in v1.4.0 to require at least grpc-go v1.62.0 of generated code. Update to v1.62.2 to require the latest security release of grpc-go.
Additionally, bump the version of the protocolbuffers/go dependency.
> Update grpc-go plugin dependency to 1.62.0

- plugins/grpc-ecosystem/gateway/source.yaml
- plugins/grpc/go/source.yaml
This PR temporarily disables 2 plugin updates:
- grpc-gateway
- go-grpc
Some patches are failing to apply. We disable them so:
1. Unblock the remainder of the plugin updates, this also keeps the changeset smaller
2. Work through the failures one by one
> Temporarily disable fetcher for grpc-gateway and go-grpc

- tests/plugins_test.go
This creates `foo/bar/baz` (`basedir`) before trying to create `foo/bar/baz/buf.gen.yaml` in our tests.
> Fix generation tests for new plugins

- internal/cmd/fetcher/main.go
This would automatically replace `# syntax=docker/dockerfile:1.7` at the top of the Dockerfile to 1.9.
> Automatically replace docker syntax to the desired version when fetching

- plugins/bufbuild/es/v2.0.0/buf.plugin.yaml
- tests/testdata/buf.build/bufbuild/es/v2.0.0/eliza/plugin.sum
- tests/testdata/buf.build/bufbuild/es/v2.0.0/petapis/plugin.sum
This PR adds the plugin option `import_extension=js` to the `bufbuild/es` plugin.
@timostamm, correct me if I'm wrong, but in v1 the default was `.js`, which means we always generated imports with extensions. But in v2, the default is none.
However, I believe this breaks BSR-generated SDKs that have dependencies and setting the above should fix it.
A reproducible example is:
```
npm init -y
npm config set @buf:registry https://buf.build/gen/npm/v1/
npm install @buf/acme_petapis.bufbuild_es@latest
```
I'd expect this to work:
```js
import { GetPetRequestSchema } from "@buf/acme_petapis.bufbuild_es/pet/v1/pet_pb.js";
import { create, toJson } from "@bufbuild/protobuf";
let request = create(GetPetRequestSchema, {
petId: "123",
});
const json = toJson(GetPetRequestSchema, request); …
```
> Add import_extension option to bufbuild/es v2

- plugins/community/neoeinstein-prost/v0.3.1/buf.plugin.yaml
This option will change the generated code for the protobuf `bytes` type fields from `Vec<u8>` types to `bytes::Bytes` types from the `bytes` crate. We believe that this type is more ergonomic in most cases for most users, and that the additional dependency is warranted for Generated SDKs.
> Set `bytes=.` option for community/neoeinstein-prost generated SDKs

- tests/plugins_test.go
In addition to checking that dependencies exist for the full (default) runtime, we should also ensure any dependencies of the lite runtime exist as well.
> Check for Maven lite dependencies

- plugins/apple/swift/v1.28.1/.dockerignore
- plugins/apple/swift/v1.28.1/Dockerfile
- plugins/apple/swift/v1.28.1/buf.plugin.yaml
- plugins/apple/swift/v1.28.1/extramoduleimports.patch
- tests/testdata/buf.build/apple/swift/v1.28.1/eliza/plugin.sum
- tests/testdata/buf.build/apple/swift/v1.28.1/petapis/plugin.sum
Update apple/swift plugin (patch needed to be recreated).
Fixes #1464.
> Add apple/swift v1.28.1 plugin

- cmd/latest-plugins/main.go
Update the latest-plugins command to support an --include-file parameter, which when used will include all of the plugin names/versions from the file in addition to the latest versions of all plugins in the output.
This also ensures that if there are newer revisions to existing plugins, they'll also be updated to the latest.
> Update latest-plugins to support include file

- plugins/community/google-gnostic-openapi/v0.7.0/buf.plugin.yaml
Fixes https://github.com/bufbuild/plugins/issues/1519
> Remove output_language because it should be 'other' and not 'go'

- plugins/apple/swift/v1.28.2/.dockerignore
- plugins/apple/swift/v1.28.2/Dockerfile
- plugins/apple/swift/v1.28.2/buf.plugin.yaml
- plugins/apple/swift/v1.28.2/extramoduleimports.patch
- tests/testdata/buf.build/apple/swift/v1.28.2/eliza/plugin.sum
- tests/testdata/buf.build/apple/swift/v1.28.2/petapis/plugin.sum
Needed to fix up the patch, as the upstream adopted `swift-format`: https://github.com/apple/swift-protobuf/releases/tag/1.28.2.
Fixes #1529.
> Add apple/swift v1.28.2 plugin

- plugins/protocolbuffers/go/v1.35.1/.dockerignore
- plugins/protocolbuffers/go/v1.35.1/Dockerfile
- plugins/protocolbuffers/go/v1.35.1/buf.plugin.yaml
- tests/testdata/buf.build/protocolbuffers/go/v1.35.1/eliza/plugin.sum
- tests/testdata/buf.build/protocolbuffers/go/v1.35.1/petapis/plugin.sum
Needed to bump `min_version` to `1.21` after https://github.com/protocolbuffers/protobuf-go/commit/af06170887211da1ad1a291ed3b9fb1247e6680d.
Fixes #1537.
> Add protocolbuffers/go v1.35.1 plugin

- plugins/grpc/cpp/v1.67.1/Dockerfile
- plugins/grpc/csharp/v1.67.1/Dockerfile
- plugins/grpc/objc/v1.67.1/Dockerfile
- plugins/grpc/php/v1.67.1/Dockerfile
- plugins/grpc/python/v1.67.1/Dockerfile
- plugins/grpc/ruby/v1.67.1/Dockerfile
Avoid some issues with local development plugin builds by switching to bazelisk and building as non-root.
> Build grpc with bazelisk as non-root

- plugins/grpc/cpp/v1.67.1/Dockerfile
- plugins/grpc/csharp/v1.67.1/Dockerfile
- plugins/grpc/objc/v1.67.1/Dockerfile
- plugins/grpc/php/v1.67.1/Dockerfile
- plugins/grpc/python/v1.67.1/Dockerfile
- plugins/grpc/ruby/v1.67.1/Dockerfile
When building on macOS with the docker-container driver, there are errors connecting between the server and client used internally by bazel. It appears that the server binds to `[::1]:0` and the client for some reason can't connect.
Update to specify that the server should prefer IPv4 over IPv6 addresses, which appears to resolve the issue.
> Ensure bazel server starts on IPv4 only

- .github/docker/Dockerfile.distroless-java-debian
Update distroless Java from 17 to 21 (has been the LTS since 2023-09).
> Update Java to 21

- plugins/protocolbuffers/csharp/v28.3/buf.plugin.yaml
- plugins/protocolbuffers/csharp/v28.3/build.csproj
.NET 9 SDK [raises](https://learn.microsoft.com/en-ca/dotnet/core/compatibility/sdk/9.0/netstandard-warning) a (suppressable) build warning about this, largely to encourage developers to upgrade. This should not be an issue for consumers, as the more important consideration is the hosting application's target framework.
More importantly, using `netstandard1.1` results in a vulnerable version of `System.Net.Http` being pulled in (`4.3.0`) via `Google.Protobuf`'s `netstandard1.1` deps. Upgrading to `netstandard2.0` resolves this.
`grpc/csharp` is already using `netstandard2.0`. No other C# plugins exist.
> Bump `protocolbuffers/csharp@28.3` to `netstandard2.0`

- plugins/bufbuild/connect-es/v0.13.0/buf.plugin.yaml
- plugins/bufbuild/connect-query/v0.4.1/buf.plugin.yaml
- plugins/bufbuild/es/v2.2.2/buf.plugin.yaml
- plugins/connectrpc/es/v1.6.1/buf.plugin.yaml
- plugins/connectrpc/query-es/v1.4.2/buf.plugin.yaml
This PR marks the following plugins as deprecated with a new description:
- https://buf.build/connectrpc/es
- https://buf.build/connectrpc/query-es
And updates the description for:
- https://buf.build/bufbuild/connect-es (previously deprecated)
- https://buf.build/bufbuild/connect-query (previously deprecated)
- https://github.com/bufbuild/protobuf-es
After this is merged/released, I'll make them as `disabled: true` in the source. I don't recall if we use that for any logic outside the fetcher.
> Deprecate connectrpc es and query-es

- plugins/googlecloudplatform/bq-schema/source.yaml
Temporarily disable this plugin until we hear back on https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema/pull/52
Would like to get the fetcher job green.
> Disable protoc-gen-bq-schema sync

- plugins/protocolbuffers/cpp/v28.3/Dockerfile
- plugins/protocolbuffers/csharp/v28.3/Dockerfile
- plugins/protocolbuffers/java/v28.3/Dockerfile
- plugins/protocolbuffers/kotlin/v28.3/Dockerfile
- plugins/protocolbuffers/objc/v28.3/Dockerfile
- plugins/protocolbuffers/php/v28.3/Dockerfile
- plugins/protocolbuffers/pyi/v28.3/Dockerfile
- plugins/protocolbuffers/python/v28.3/Dockerfile
- plugins/protocolbuffers/ruby/v28.3/Dockerfile
For older plugins which use bazelisk, pin a version of bazel to avoid build failures when attempting to build with Bazel 8.x.
> Pin bazel version for reproducible builds

- plugins/googlecloudplatform/bq-schema/source.yaml
The bq-schema plugin was released with version v3.0 which doesn't work with Go install. Ignore this version and wait for the next release.
> Ignore bq-schema plugin version v3.0

- .github/docker/Dockerfile.bazel
- internal/cmd/fetcher/main.go
- internal/docker/baseimage_test.go
We now use Bazel with bazelisk and pin exact versions (either the version specified in .bazelversion or in an env var). Remove Docker image for bazel and code to auto update Bazel in the fetcher.
> Stop updating Bazel version in builds

- plugins/connectrpc/dart/source.yaml
Update config to ignore this version of the plugin - we'll pick up v0.2.1 when it is published.
Fixes #1687.
> Ignore v0.2.0 of connectrpc-dart

- plugins/grpc/swift/source.yaml
With v2.0.0, the protoc plugin for grpc-swift now exists in a separate grpc-swift-protobuf project. Unfortunately, the two projects are no longer versioned together, so we'll need to brainstorm the best way to support this plugin going forward.
For now, disable updates for this plugin to allow other updates to proceed.
> Disable grpc/swift fetcher

- .github/workflows/fetch_versions.yml
- .github/workflows/release.yml
- .github/workflows/upload.yml
To prevent getting caught in rate limits.
> Use github app to create issues

- .github/workflows/arm64.yml
- .github/workflows/ci.yml
- .github/workflows/fetch_versions.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/restore-release.yml
- .github/workflows/upload.yml
Update workflows to add a version comment (that will be kept updated by dependabot) to all third party actions which are pinned to a commit hash.
> Add version comments to GitHub workflows

- plugins/protocolbuffers/dart/v22.2.0/.dockerignore
- plugins/protocolbuffers/dart/v22.2.0/Dockerfile
- plugins/protocolbuffers/dart/v22.2.0/buf.plugin.yaml
- tests/testdata/buf.build/protocolbuffers/dart/v22.2.0/eliza/plugin.sum
- tests/testdata/buf.build/protocolbuffers/dart/v22.2.0/petapis/plugin.sum
Update protocolbuffers/dart plugin to the latest, which required tweaking the build to compile from a git clone instead of the release tarball (changed to use workspace dependencies).
Fixes #1841.
> Add protocolbuffers/dart v22.2.0

- Makefile
- cmd/download-plugins/main.go
Use the higher level GitHub client to make requests to ensure we correctly handle rate limit errors.
> Use GitHub client instead of http client

- plugins/grpc/swift-protobuf/source.yaml
Reverts bufbuild/plugins#1961
The plugin is still located at grpc-swift-protobuf, however the libraries it use moved to a new location. There is no new version of this plugin yet.
> Revert "Update source for grpc/swift-protobuf"

- .envrc
- Makefile
So that dependency binaries are usable outside of the Makefile.
> Add .tmp/ dir to $PATH

- plugins/protocolbuffers/pyi/v32.1/buf.plugin.yaml
- plugins/protocolbuffers/python/v32.1/buf.plugin.yaml
The previous specifiers were too restrictive of maximum values; we _know_ the minimum version that we want to allow, but we leave it up to users to determine their maximum. (Newer versions of the `protobuf` runtime should support previous versions of gencode, [at least up to the next major version][1], but possibly further in practice.)
In terms of `types-protobuf`, the versions simply match the version of the runtime, and so similarly should not have an upper bound.
[1]: https://protobuf.dev/support/cross-version-runtime-guarantee/#major
> Change Python version specifiers for protobuf to `>=`
