bufbuild/plugins

.github/workflows/fetch_versions.yml

This PR reduces the frequency fetching upstream plugin versions. Changes from every 4 hours to once a day.

Reduce fetching frequency

---

.github/workflows/ci.yml
.github/workflows/pr.yml

Update images published from the main CI build to ghcr.io (for future
caching).

push images from main CI build to ghcr.io

---

.github/workflows/ci.yml
.github/workflows/pr.yml
Makefile

Use the ghcr.io images with --cache-from to optimize build times.

specify --cache-from when building

---

.github/dependabot.yml

Add dependabot configuration for docker.

configure dependabot for Docker

---

.github/workflows/deploy.yml
library/connect-go/v0.1.1/Dockerfile
library/connect-go/v0.2.0/Dockerfile
library/connect-go/v0.3.0/Dockerfile
library/connect-go/v0.4.0/Dockerfile

Add '--debug' to plugin push command. Pull the plugin image (if it
exists) prior to build. Simplify connect-go Dockerfile to remove
unnecessary layers.

add --debug arg to deployment step

---

.github/workflows/ci.yml

This reverts commit 9e0fb9a17a72724106d2a942b306b3c078f5917e.

Revert "load built images into Docker (#30)"

---

.github/workflows/ci.yml

This reverts commit 19f40837e4d88e172b8025e2b0a0c698c33a29d3.

Revert "Remove pushing all plugins (#37)"

---

.github/ISSUE_TEMPLATE/plugin-request-for-buf-schema-registry.md

This PR adds an issue template to request new plugins to be added to the BSR.

Update issue templates

---

internal/fetchclient/fetchclient.go

Maven versions can be returned out of order (the default sort is by score). Update the query to determine the latest semver version from the API (ignoring pre-release versions).
Additionally, fetch the latest patch version for each major+minor (we can update the utility in the future to use this to update to later patch versions of plugins we already ship).

update fetcher to retrieve latest version

---

tests/plugins_test.go

Update plugins_test to add a new test to validate buf.plugin.yaml for all plugins.

add test to validate buf.plugin.yaml

---

plugins/grpc/cpp/v1.49.1/Dockerfile
plugins/grpc/csharp/v1.49.1/Dockerfile
plugins/grpc/objc/v1.49.1/Dockerfile
plugins/grpc/php/v1.49.1/Dockerfile
plugins/grpc/python/v1.49.1/Dockerfile
plugins/grpc/ruby/v1.49.1/Dockerfile
plugins/protocolbuffers/cpp/v21.7/Dockerfile
plugins/protocolbuffers/csharp/v21.7/Dockerfile
plugins/protocolbuffers/java/v21.7/Dockerfile
plugins/protocolbuffers/kotlin/v21.7/Dockerfile
plugins/protocolbuffers/objc/v21.7/Dockerfile
plugins/protocolbuffers/php/v21.7/Dockerfile
plugins/protocolbuffers/python/v21.7/Dockerfile
plugins/protocolbuffers/ruby/v21.7/Dockerfile

This resolves an issue seen with cross compilation (/proc/self/exe panic).

update to latest bazel for builds

---

plugins/apple/swift/v1.20.2/buf.plugin.yaml
plugins/bufbuild/connect-go/v1.0.0/buf.plugin.yaml
plugins/bufbuild/connect-web/v0.2.1/buf.plugin.yaml
plugins/bufbuild/protobuf-es/v0.1.1/buf.plugin.yaml
plugins/bufbuild/validate-cpp/v0.6.13/buf.plugin.yaml
plugins/bufbuild/validate-go/v0.6.13/buf.plugin.yaml
plugins/bufbuild/validate-java/v0.6.13/buf.plugin.yaml
plugins/community/chrusty-jsonschema/v1.3.9/buf.plugin.yaml
plugins/grpc/cpp/v1.49.1/buf.plugin.yaml
plugins/grpc/csharp/v1.49.1/buf.plugin.yaml
plugins/grpc/go/v1.2.0/buf.plugin.yaml
plugins/grpc/java/v1.49.2/buf.plugin.yaml
plugins/grpc/kotlin/v1.3.0/buf.plugin.yaml
plugins/grpc/objc/v1.49.1/buf.plugin.yaml
plugins/grpc/php/v1.49.1/buf.plugin.yaml
plugins/grpc/python/v1.49.1/buf.plugin.yaml
plugins/grpc/ruby/v1.49.1/buf.plugin.yaml
plugins/grpc/swift/v1.11.0/buf.plugin.yaml
plugins/protocolbuffers/cpp/v21.7/buf.plugin.yaml
plugins/protocolbuffers/csharp/v21.7/buf.plugin.yaml
plugins/protocolbuffers/dart/v20.0.1/buf.plugin.yaml
plugins/protocolbuffers/go/v1.28.1/buf.plugin.yaml
plugins/protocolbuffers/java/v21.7/buf.plugin.yaml
plugins/protocolbuffers/kotlin/v21.7/buf.plugin.yaml
plugins/protocolbuffers/objc/v21.7/buf.plugin.yaml
plugins/protocolbuffers/php/v21.7/buf.plugin.yaml
plugins/protocolbuffers/python/v21.7/buf.plugin.yaml
plugins/protocolbuffers/ruby/v21.7/buf.plugin.yaml

Make a pass to update the descriptions of plugins to better describe what they do.

update descriptions for plugins

---

.github/workflows/ci.yml
.github/workflows/fetch_versions.yml
.github/workflows/pr.yml
.github/workflows/push_all.yml

Update to use native caching built-in to actions/setup-go.

simplify go caching in workflows

---

.github/ISSUE_TEMPLATE/plugin-request-for-buf-schema-registry.md

Just some minor tweaks, after going through the process in #219.
* Don't need to ask about default options currently
* Tweak formatting of final section, to separate out last question and "not ready to open an issue" section

Tweak plugin request template

---

internal/fetchclient/fetchclient.go
internal/source/config.go

Fix #252
Tested once.
```
2022/12/02 18:16:56 [DEBUG] GET https://crates.io/api/v1/crates/protoc-gen-prost
2022/12/02 18:16:57 v0.2.1
```

Add crates.io API support in fetchclient

---

cmd/download-plugins/main.go

Check if the downloaded plugin exists before checking its digest.

fix download command for new plugins

---

internal/fetchclient/fetchclient.go

Instead of dealing w/ the rest API (and pagination), simply fetch the maven-metadata.xml file and determine versions from there.

switch fetcher to use maven-metadata.xml

---

plugins/grpc-ecosystem/openapiv2/source.yaml
plugins/grpc-ecosystem/openapiv2/v2.15.0/.dockerignore
plugins/grpc-ecosystem/openapiv2/v2.15.0/Dockerfile
plugins/grpc-ecosystem/openapiv2/v2.15.0/buf.plugin.yaml
tests/testdata/buf.build/grpc-ecosystem/openapiv2/v2.15.0/eliza/plugin.sum
tests/testdata/buf.build/grpc-ecosystem/openapiv2/v2.15.0/petapis/plugin.sum

Add the protoc-gen-openapiv2 plugin from grpc-gateway.
Fixes #250.

add grpc-ecosystem/openapiv2 plugin

---

plugins/bufbuild/connect-query/source.yaml
plugins/bufbuild/connect-query/v0.1.0/.dockerignore
plugins/bufbuild/connect-query/v0.1.0/Dockerfile
plugins/bufbuild/connect-query/v0.1.0/buf.plugin.yaml
plugins/bufbuild/connect-query/v0.1.0/package-lock.json
plugins/bufbuild/connect-query/v0.1.0/package.json
tests/testdata/buf.build/bufbuild/connect-query/v0.1.0/eliza/plugin.sum
tests/testdata/buf.build/bufbuild/connect-query/v0.1.0/petapis/plugin.sum

Create a plugin for bufbuild/connect-query.
Fixes #328.

Add connect-query v0.1.0 plugin

---

.github/workflows/release.yml

This was working properly with `needs` and `uses`, but apparently not when we added additional attributes.

Attempt to fix release workflow again

---

plugins/bufbuild/connect-es/source.yaml

This will enable detecting new versions of the connect-es plugin.

Add connect-es source configuration

---

plugins/community/planetscale-vtprotobuf/source.yaml
plugins/community/planetscale-vtprotobuf/v0.4.0/.dockerignore
plugins/community/planetscale-vtprotobuf/v0.4.0/Dockerfile
plugins/community/planetscale-vtprotobuf/v0.4.0/buf.plugin.yaml
tests/testdata/buf.build/community/planetscale-vtprotobuf/v0.4.0/eliza/plugin.sum
tests/testdata/buf.build/community/planetscale-vtprotobuf/v0.4.0/petapis/plugin.sum

Add planetscale-vtprotobuf remote plugin

---

.github/dependabot.yml

Meant to change this in the last PR.

Change dependabot to update base images daily

---

.github/docker/Dockerfile.python

We're going to add some plugins that use python - go ahead and add a new file to track python upgrades.

Add dockerfile for python base image

---

.github/workflows/ci.yml

Revert "Disable changed files calculation to reset state"

---

plugins/community/mitchellh-go-json/source.yaml
plugins/community/mitchellh-go-json/v1.1.0/.dockerignore
plugins/community/mitchellh-go-json/v1.1.0/Dockerfile
plugins/community/mitchellh-go-json/v1.1.0/buf.plugin.yaml
tests/testdata/buf.build/community/mitchellh-go-json/v1.1.0/eliza/plugin.sum
tests/testdata/buf.build/community/mitchellh-go-json/v1.1.0/petapis/plugin.sum

Add community/mitchellh-go-json plugin

---

.github/ISSUE_TEMPLATE/plugin-request-for-buf-schema-registry.md

- Remove the remote packages compatibility question
- Update the runtime dependency question for clarity

Update the plugin request issue template

---

internal/cmd/fetcher/main.go

Fix fetch versions

---

plugins/bufbuild/connect-query/v0.4.1/.dockerignore
plugins/bufbuild/connect-query/v0.4.1/Dockerfile
plugins/bufbuild/connect-query/v0.4.1/buf.plugin.yaml
plugins/bufbuild/connect-query/v0.4.1/package-lock.json
plugins/bufbuild/connect-query/v0.4.1/package.json
plugins/community/scalapb-zio-grpc/v0.6.0/.dockerignore
plugins/community/scalapb-zio-grpc/v0.6.0/Dockerfile
plugins/community/scalapb-zio-grpc/v0.6.0/buf.plugin.yaml
plugins/community/stephenh-ts-proto/v1.156.5/.dockerignore
plugins/community/stephenh-ts-proto/v1.156.5/Dockerfile
plugins/community/stephenh-ts-proto/v1.156.5/buf.plugin.yaml
plugins/community/stephenh-ts-proto/v1.156.5/package-lock.json
plugins/community/stephenh-ts-proto/v1.156.5/package.json
tests/testdata/buf.build/bufbuild/connect-query/v0.4.1/eliza/plugin.sum
tests/testdata/buf.build/bufbuild/connect-query/v0.4.1/petapis/plugin.sum
tests/testdata/buf.build/community/scalapb-zio-grpc/v0.6.0/eliza/plugin.sum
tests/testdata/buf.build/community/scalapb-zio-grpc/v0.6.0/petapis/plugin.sum
tests/testdata/buf.build/community/stephenh-ts-proto/v1.156.5/eliza/plugin.sum
tests/testdata/buf.build/community/stephenh-ts-proto/v1.156.5/petapis/plugin.sum

- community/stephenh-ts-proto/v1.156.5
- community/scalapb-zio-grpc/v0.6.0
- bufbuild/connect-query/v0.4.1

Update bufbuild and community plugins

---

.github/workflows/ci.yml
.github/workflows/fetch_versions.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/restore-release.yml
.github/workflows/upload.yml

Update the runner size for ci, pr, and fetch_versions workflows from 2 to 4 cores.

Increase github runner sizes

---

.github/docker/Dockerfile.python

Dependabot didn't pick up this upgrade automatically.

Update python image to alpine 3.19

---

plugins/community/stephenh-ts-proto/source.yaml

Related to https://github.com/bufbuild/plugins/issues/1039

Temporarily disable community/stephenh-ts-proto updates

---

.github/workflows/arm64.yml
.github/workflows/ci.yml
.github/workflows/fetch_versions.yml
.github/workflows/golangci-lint.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/restore-release.yml
.github/workflows/upload.yml
.golangci.yml
CONTRIBUTING.md
cmd/latest-plugins/main.go
go.mod
internal/cmd/dockerbuild/main.go
internal/cmd/release/main.go
tests/plugins_test.go

Update to go 1.22 and address lint errors.

Update to go 1.22

---

README.md

This updates the README.md to clarify what sorts of plugins we are likely to accept into this repo, and what other options exist (custom plugins).

Update README.md regarding custom plugins

---

plugins/bufbuild/protoschema-bigquery/v0.1.0/buf.plugin.yaml
plugins/bufbuild/protoschema-bigquery/v0.1.1/buf.plugin.yaml
plugins/bufbuild/protoschema-bigquery/v0.1.2/buf.plugin.yaml
plugins/bufbuild/protoschema-bigquery/v0.1.3/buf.plugin.yaml
plugins/bufbuild/protoschema-jsonschema/v0.1.0/buf.plugin.yaml
plugins/bufbuild/protoschema-jsonschema/v0.1.1/buf.plugin.yaml
plugins/bufbuild/protoschema-jsonschema/v0.1.2/buf.plugin.yaml
plugins/bufbuild/protoschema-jsonschema/v0.1.3/buf.plugin.yaml
plugins/bufbuild/protoschema-pubsub/v0.1.0/buf.plugin.yaml
plugins/bufbuild/protoschema-pubsub/v0.1.1/buf.plugin.yaml
plugins/bufbuild/protoschema-pubsub/v0.1.2/buf.plugin.yaml
plugins/bufbuild/protoschema-pubsub/v0.1.3/buf.plugin.yaml

Removes the archive registry config.

Remove registry.archive

---

plugins/community/timostamm-protobuf-ts/v2.9.4/Dockerfile

Revert change which trimmed the typescript module in case this is causing issues with generation of .d.ts files.
Fixes #1162.

Revert trimming of typescript module

---

plugins/grpc/node/v1.12.4/Dockerfile
plugins/grpc/node/v1.12.4/package-lock.json

Update tar to fix a moderate severity security vulnerability and upgrade Docker images to the latest version.

Update tar to fix security vulnerability

---

plugins/apple/swift/v1.26.0/Dockerfile
plugins/grpc/swift/v1.23.0/Dockerfile

Update apple/swift and grpc/swift to remove extra layers.

Reduce image layers in swift images

---

plugins/protocolbuffers/pyi/v27.1/buf.plugin.yaml
plugins/protocolbuffers/python/v27.1/buf.plugin.yaml

Update python dependencies for v27.1

---

cmd/latest-plugins/main.go

Include the latest community plugins by default but continue to skip deprecated plugins.

Update latest-plugins utility

---

.github/workflows/arm64.yml
.github/workflows/ci.yml
.github/workflows/fetch_versions.yml
.github/workflows/pr.yml

Update to ensure we log in to Docker hub in all workflows. Remove unnecessary qemu setup (we don't do cross compilation using qemu).

Ensure we log in to Docker hub in workflows

---

plugins/grpc/cpp/v1.64.0/Dockerfile
plugins/grpc/cpp/v1.64.0/buf.plugin.yaml

Note this also squashes layers since v1.64.0 did not yet support that optimization.

Add cmake support to grpc/cpp:1.64.0

---

plugins/grpc/cpp/v1.64.2/buf.plugin.yaml

Add cmake support to grpc/cpp:1.64.2

---

tests/plugins_test.go

Prior to releasing a plugin supporting Maven generated SDKs, we should ensure that all dependencies declared in the buf.plugin.yaml file are available.

Validate maven dependency availability

---

CONTRIBUTING.md

Open to suggestions if any of this needs more explaining.

Add new configuration explanation to CONTRIBUTING.md

---

plugins/community/stephenh-ts-proto/v2.2.0/.dockerignore
plugins/community/stephenh-ts-proto/v2.2.0/Dockerfile
plugins/community/stephenh-ts-proto/v2.2.0/buf.plugin.yaml
plugins/community/stephenh-ts-proto/v2.2.0/package-lock.json
plugins/community/stephenh-ts-proto/v2.2.0/package.json
tests/testdata/buf.build/community/stephenh-ts-proto/v2.2.0/eliza/plugin.sum
tests/testdata/buf.build/community/stephenh-ts-proto/v2.2.0/petapis/plugin.sum

Add stephenh-ts-proto v2.2.0

---

plugins/grpc/swift-protobuf/source.yaml
plugins/grpc/swift-protobuf/v1.0.0/.dockerignore
plugins/grpc/swift-protobuf/v1.0.0/Dockerfile
plugins/grpc/swift-protobuf/v1.0.0/buf.plugin.yaml
tests/testdata/buf.build/grpc/swift-protobuf/v1.0.0/eliza/plugin.sum
tests/testdata/buf.build/grpc/swift-protobuf/v1.0.0/petapis/plugin.sum

Currently at v1.0.0.
Resolves #1696.

Add grpc/swift-protobuf

---

plugins/connectrpc/swift-mocks/v1.0.2/buf.plugin.yaml
plugins/connectrpc/swift/v1.0.2/buf.plugin.yaml

Should have done this in #1729, oops.

Bump connectrpc/swift apple/swift deps to latest

---

.github/workflows/ci.yml
.github/workflows/pr.yml

Update to the latest commit revision after the previous tag has been recreated.

Update tj-actions/changed-files commit

---

.github/docker/Dockerfile.python
plugins/connectrpc/python/source.yaml
plugins/connectrpc/python/v0.4.2/.dockerignore
plugins/connectrpc/python/v0.4.2/Dockerfile
plugins/connectrpc/python/v0.4.2/buf.plugin.yaml
plugins/connectrpc/python/v0.4.2/requirements.txt
tests/testdata/buf.build/connectrpc/python/v0.4.2/eliza/plugin.sum
tests/testdata/buf.build/connectrpc/python/v0.4.2/petapis/plugin.sum

Starting with v0.4.2, the initial/latest version.

Add support for connectrpc/python

---

.github/workflows/fetch_versions.yml
.github/workflows/release.yml
.github/workflows/upload.yml

Update App Token Workflow to Latest

---

plugins/grpc/web/source.yaml

Remove ignore for grpc-web v2.0.0

---

plugins/connectrpc/go/v1.19.0/.dockerignore
plugins/connectrpc/go/v1.19.0/Dockerfile
plugins/connectrpc/go/v1.19.0/buf.plugin.yaml
tests/testdata/buf.build/connectrpc/go/v1.19.0/eliza/plugin.sum
tests/testdata/buf.build/connectrpc/go/v1.19.0/petapis/plugin.sum

Update connectrpc/go to v1.19.0
